### ISSUE TITLE
Can add api_endpoint option for deepseek?

### ISSUE THREAD

**Issue by mei-rune** [yomorun/yomo#1029]
Can add api_endpoint option for deepseek?

**Comment by fanweixiao** [comment]
Hello @mei-rune,

Are you referring to the self-hosted DeepSeek model? You can serve DeepSeek models using either [vllm](https://github.com/vllm/vllm) or [ollama](https://github.com/ollama/ollama). Both of these libraries have already been supported. To enable DeepSeek, update your `yomo.yml` file as follows:

```yaml
name: ai-zipper
host: 0.0.0.0
port: 9000

bridge:
  ai:
    server:
      addr: 0.0.0.0:9000
      provider: vllm-seekseek

    providers:
      vllm-deepseek:
        api_endpoint: http://34.64.203.112:9999/v1
        api_key: <YOUR_VLLM_API_KEY>
        model: deepseek-ai/DeepSeek-R1-Distill-Llama-70B

      ollama-deepseek:
        api_endpoint: http://localhost:11434

      deepseek-official:
        api_key: <YOUR_DEEPSEEK_API_KEY>
        model: deepseek-reasoner
```

With this configuration, you can select which API your LLM agents will use.
