### ISSUE TITLE
Simplify workflow.yaml

### ISSUE THREAD

**Issue by xiaojian-hong** [yomorun/yomo#174]
We will rename source/flow/sink in #173, and it's also not needed to place `sinks` in `workflow.yaml`.

- Remove `sinks`
- Rename `flows` to `functions`
- Connect `output` connectors to `yomo` and receive the output data in parallel. 

```yaml
name: Service
host: localhost
port: 9000
functions:
  - name: func1
  - name: func2
```
